### ISSUE TITLE
비밀번호 없이 제출 막힘

### ISSUE THREAD

**Issue by ownstj** [eduro-hcs/jaga_jindan#4]
이번 업데이트로 인해 비밀번호 없이 제출시 이전버전에서는 제출 오류라 뜨고 새 버전에는 비밀번호 오류라고 나옵니다.

보안을 조금더 강화시킨 거 같아 해당 기능을 다음 업데이트부터 없앴으면 좋겠습니다

**Comment by nnnlog** [comment]
말씀하신대로 12월 13일 자정부터 자가진단 웹페이지 업데이트로 인해 비밀번호 없이 제출할 수 없습니다.
#3 에 통합하여 처리하겠습니다. 감사합니다.
